# YAML doc:  https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema

resources:
- repo: self
# configure a CI trigger on master branch.
trigger: 
- master

# Stages:  https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema#stage
stages:
- stage:  Packaging / Initializing
  jobs:
  - job:  Packaging
#   apply the default agent tools. Azure Pipelines with vmImage : 'ubuntu-latest'. 
#     pool:
#       vmImage: 'ubuntu-latest'
    variables:  []
    steps:
    # Publish artefact:  https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/pipeline-artifacts#publish-artifacts
    - publish: $(System.DefaultWorkingDirectory)/bin/
      artifact:  scripts
      displayName: 'Publish Artifact:  scripts'
- stage:  Staging
  displayName:  Push to staging
  variables:  []
  jobs:
  # Template reference:  https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema#template-references
  - template: deploy-db-template.yaml
    parameters:
      env: staging
- stage:  Production
  displayName:  Push to production
  variables:  []
  jobs:
  # Template reference:  https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema#template-references
  - template: deploy-db-template.yaml
    parameters:
      env: jiaruli-pro
