# YAML doc:  https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema

resources:
- repo: self
# configure a CI trigger on master branch.
trigger: 
- master

# Stages:  https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema#stage
stages:
- stage:  Packaging
  jobs:
  - job:  Packaging
#   apply the default agent tools. Azure Pipelines with vmImage : 'ubuntu-latest'. 
#     pool:
#       vmImage: 'ubuntu-latest'
    variables:  []
    steps:
    - publish: $(Pipeline.Workspace)/
      artifact:  documents
      displayName: 'Publish Artifact:  documents'
- stage:  Staging
  displayName:  Download scripts from development environment
  variables:  []
  jobs:
  - template: deploy-db-download.yaml
    parameters:
      env: eq-dev 
- stage:  Production
  displayName:  Push scripts to production environment
  variables:  []
  jobs:
  - template: deploy-db-push.yaml
    parameters:
      env: jiaruli-pro
