# YAML doc:  https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema

resources:
- repo: self
# Triggers:  https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema#triggers
trigger: none

# Stages:  https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema#stage
stages:
- stage:  Packaging
  jobs:
  - job:  Packaging
#     pool:
#       vmImage: 'ubuntu-latest'
    variables:  []
    steps:
    - bash: |
       # Fails if one of the command fails in the script
        set -e
        mkdir -p documentation/d2p
      displayName:  Prep scripts folder
    # Publish artefact:  https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/pipeline-artifacts#publish-artifacts
    - publish: documentation/d2p
      artifact:  scripts
      displayName: 'Publish Artifact:  scripts'
- stage:  Staging
  displayName:  Push to staging
  variables:  []
  jobs:
  # Template reference:  https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema#template-references
  - template: deploy-db-template.yaml
    parameters:
      env: jiaruli-dev
- stage:  Production
  displayName:  Push to production
  variables:  []
  jobs:
  # Template reference:  https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema#template-references
  - template: deploy-db-template.yaml
    parameters:
      env: jiaruli-pro
