# YAML doc:  https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema

resources:
- repo: self
# configure a CI trigger on master branch.
trigger: 
- master

# Stages:  https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema#stage
stages:
- stage:  Packaging
  jobs:
  - job:  Packaging
#   apply the default agent tools. Azure Pipelines with vmImage : 'ubuntu-latest'. 
#     pool:
#       vmImage: 'ubuntu-latest'
    variables:  []
    steps:
    - script: dir
      workingDirectory: $(Agent.BuildDirectory)
      displayName: List contents of a folder
    - publish: $(Pipeline.Workspace)/
      artifact:  scripts
      displayName: 'Publish Artifact:  scripts'
- stage: Verification
  jobs: 
  - job: Path Verification
    steps:
    - scripts: dir
      which "deploy-db-template.yaml"
      displayName: 'Found the path to the yaml file.'
- stage:  Staging
  displayName:  Push to staging
  variables:  []
  jobs:
  # Template reference:  https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema#template-references
  - template: deploy-db-template.yaml
    parameters:
      env: stagings 
- stage:  Production
  displayName:  Push to production
  variables:  []
  jobs:
  # Template reference:  https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema#template-references
  - template: deploy-db-template.yaml
    parameters:
      env: jiaruli-pro
