sendErrorOptIn:  true
jobs:
  download-dev:
    target:
        adx:
            clusterUri:  to-be-overriden
            database:  to-be-overriden
    action:
        folderPath:  ../dev-update
        pushToConsole:  true
