sendErrorOptIn:  true
jobs:
  download-dev:
    target:
        adx:
            clusterUri:  to-be-overriden
            database:  to-be-overriden
    action:
        filePath:  ../dev-update/dev-update.kql
        pushToCurrent:  true
        pushToConsole:  true
