sendErrorOptIn:  true
jobs:
  push-script-to-prod:
    current:
        adx:
            clusterUri:  to-be-overriden
            database:  to-be-overriden
    target:
        scripts:
        - folderPath:  ../dev-update
    action:
        folderPath: ../prod-update
        pushToCurrent:  true
        pushToConsole:  true
