# push to uat / prod, push target scripts to current db 
sendErrorOptIn:  true
jobs:
  push-script-to-prod:
    current:
        adx:
            clusterUri:  to-be-overriden
            database:  to-be-overriden
    target:
        scripts:
        - filePath:  ../dev-update/dev-update.kql
    action:
        filePath: ../prod-update/prod-udpate.kql
        pushToCurrent:  true
        pushToConsole:  true
